#!/usr/bin/env sh

DOTFILES="$(cd "$(dirname "$0")" && pwd)"

# Neovim
rm -rf $HOME/.config/nvim
ln -s $DOTFILES/nvim $HOME/.config/nvim

# Tmux
ln -sf $DOTFILES/tmux/tmux.conf $HOME/.tmux.conf

# Git
ln -sf $DOTFILES/git/gitconfig $HOME/.gitconfig
ln -sf $DOTFILES/git/gitignore_global $HOME/.gitignore_global

#LazyGit
ln -sf $DOTFILES/lazygit/config.yml $HOME/.config/lazygit/config.yml

# Phpactor
rm -rf $HOME/.config/phpactor
ln -s $DOTFILES/phpactor $HOME/.config/phpactor

# Scripts
mkdir -p $HOME/.local/bin

ln -sf $DOTFILES/scripts/t $HOME/.local/bin/t
ln -sf $DOTFILES/scripts/deliver $HOME/.local/bin/deliver

# NVM (Node Version Manager)
mkdir -p $HOME/.nvm
ln -sf $DOTFILES/nvm/default-packages $HOME/.nvm/default-packages

# Bash
ln -sf $DOTFILES/bash/bash_aliases $HOME/.bash_aliases
ln -sf $DOTFILES/bash/bashrc $HOME/.bashrc
ln -sf $DOTFILES/bash/bash_colors $HOME/.bash_colors
