alias dotfiles="cd ~/code/dotfiles"
alias ealias="vim ~/.bash_aliases"
alias ebash="vim ~/.bashrc"
alias sbash="source ~/.bashrc"
alias egitconfig="vim ~/.gitconfig"

alias tmn="tmux new -s"

# some more ls aliases
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

alias cls='clear'

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    #alias dir='dir --color=auto'
    #alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

# Add an "alert" alias for long running commands.  Use like so:
#   sleep 10; alert
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'
# Vim alias
alias vim='nvim'

# alias for tmux to load correct colors
alias tmux="TERM=screen-256color-bce tmux"
alias tma="tmux attach -t"
alias tmn="tmux new -s"


# Laravel alias
alias sail="./vendor/bin/sail"
alias a="php artisan"
alias s="sail"

#Windows Navigation
alias win="cd /mnt/c/Users/gardg" 
alias desk="cd /mnt/c/Users/gardg/OneDrive/Desktop/"
alias docs="cd /mnt/c/Users/gardg/Documents"

#Update Packages
alias supdate="sudo apt-get update && sudo apt-get upgrade"
