alias dotfiles="cd ~/code/dotfiles"
alias ealias="vim ~/.bash_aliases"
alias ebash="vim ~/.bashrc"
alias sbash="source ~/.bashrc"
alias egitconfig="vim ~/.gitconfig"

alias tmn="tmux new -s"

# some more ls aliases
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

alias cls='clear'


# Add an "alert" alias for long running commands.  Use like so:
#   sleep 10; alert
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'
# Vim alias
alias vim='nvim'

# tmux alias
alias tmux="TERM=screen-256color-bce tmux"
alias tma="tmux attach -t"
alias tmn="tmux new -s"
alias tmk="tmux kill-session -t"

# tmuxinator alias
alias tms="tmuxinator s"


# Laravel alias
alias sail="./vendor/bin/sail"
alias a="php artisan"
alias s="sail"
